### ISSUE TITLE
SAMPE-client linux?

### ISSUE THREAD

**Issue by sodomon2** [dashr9230/SAMPE#13]
Hi, I was wondering if the SAMPE(client) could be compiled in linux since I see that you can only compile

**Comment by dashr9230** [comment]
To my knowledge, Visual Studio and/or it's compiler doesn't work on linux, but it can be compiled on MinGW's G++, which on some linux OSes already has this package preinstalled, but you'll need a makefile, which SAMPE doesn't have it, so you have to make your own one. Or there's a second option, which is to install VirtualBox and create Windows 8.1/10 virtual machine, if you don't want to do dual boot, and compile it in there.

**Comment by sodomon2** [comment]
ok, then I will try to make a makefile for the SAMPE

**Comment by AmyrAhmady** [comment]
Or you can use docker :)
